# Generated by Django 4.0.4 on 2022-05-06 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='author',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_date',
        ),
    ]
