# Generated by Django 4.0.4 on 2022-05-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0002_remove_author_added_by_remove_author_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
